config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'customer' => 'customer#customer_view_cards'
  get 'customer/customer_add_phonenumber_to_account' => 'customer#add_phonenumber_to_account'
  patch 'customer/do_add_phonenumber_to_account' => 'customer#do_add_phonenumber_to_account'
  
  get 'business_signup'  => 'businesses#new' 
  resources :businesses
  
  get '/business_login' => 'sessions#business_new'
  post '/business_login' => 'sessions#business_create'
  delete 'business_logout' => 'sessions#business_destroy'
  
  get 'business_options' => 'businesses#options'
  get 'business_view_cards' => 'businesses#business_view_cards'
  get 'business/update_card' => 'businesses#update_card'
  patch 'business/something' => 'businesses#check_phone_number'
  get 'business/add_card' => 'businesses#add_card'
  patch 'business/do_add_card' => 'businesses#do_add_card'
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :cards

end

app/controllers/business_controller.rb
class BusinessController < ApplicationController
    def options
    end
    
    def update_card
    end
    
    def check_phone_number
        phoneno = params[:phone_number]
        bizname = params[:business_name]
        if Card.where(:phone_number => phoneno, :business_name => bizname).blank?
                redirect_to '/business/update_card', notice: "The given phone number is not associated with " + bizname + "."
        else
            do_update_card(phoneno, bizname)
        end
    end
    
    def do_update_card(phoneno, bizname)
        biz = bizname
        @card = Card.find_by(phone_number: phoneno, business_name: biz)
        if /^\d+$/.match(params[:points])
            if params[:commit] == 'Add'
                @card.points += params[:points].to_i
            elsif params[:commit] == 'Deduct'
                @card.points -= params[:points].to_i
            else
                redirect_to '/business/update_card', notice: "This failed."
            end
            
            if @card.save
                redirect_to '/business/', notice: "Card "+@card.phone_number.to_s()+" updated successfully."
            else
                redirect_to '/business/update_card', notice: "Could not save card "+@card.phone_number.to_s()+"."
            end
        else
            redirect_to '/business/update_card', notice: "The points you entered is invalid."
        end
    end
    
    
    def phone_number_not_found
    end
    
    def add_card
    end
    
    def do_add_card
        @alert = ""
        bizname = params[:business_name]
        phoneno = params[:phone_number]
        pointss = params[:points]
        if Card.where(phone_number: phoneno, business_name: bizname).blank?
            @card = Card.new
            @card.points = pointss
            @card.business_name = bizname
            @card.phone_number = phoneno
            if /^\d{10,10}$/.match(phoneno) and /^\d+/.match(pointss)
                if @card.save
                    redirect_to '/business/', notice: "Success"
                else
                    redirect_to '/business/add_card', notice:"The phone number you entered cannot be saved."
                end
            else
                redirect_to '/business/add_card', notice:"The phone number and/or points you entered is invalid."
            end
        else
            redirect_to '/business/add_card', notice: "The card with the phone number "+phoneno.to_s()+" already exists."
        end
    end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
    before_action :require_business, only: [:add_card, :update_card, :options]
    
    def options
    end
    
    def business_view_cards
        bizname = current_business.business
        @cards = Card.where(business_name: bizname)
    end
    
    def update_card
    end
    
    def check_phone_number
        phoneno = params[:phone_number]
        bizname = current_business.business
        if Card.where(:phone_number => phoneno, :business_name => bizname).blank?
                redirect_to '/business/update_card', notice: "The given phone number is not associated with " + bizname + "."
        else
            do_update_card(phoneno, bizname)
        end
    end
    
    def do_update_card(phoneno, bizname)
        biz = bizname
        @card = Card.find_by(phone_number: phoneno, business_name: biz)
        if /^\d+$/.match(params[:points])
            if params[:commit] == 'Add'
                @card.points += params[:points].to_i
            elsif params[:commit] == 'Deduct'
                @card.points -= params[:points].to_i
            else
                redirect_to '/business/update_card', notice: "This failed."
            end
            
            if @card.save
                redirect_to '/business_options', notice: "Card "+@card.phone_number.to_s()+" updated successfully."
            else
                redirect_to '/business/update_card', notice: "Could not save card "+@card.phone_number.to_s()+"."
            end
        else
            redirect_to '/business/update_card', notice: "The points you entered is invalid."
        end
    end
    
    
    def phone_number_not_found
    end
    
    def add_card
    end
    
    def do_add_card
        @alert = ""
        bizname = current_business.business
        phoneno = params[:phone_number]
        pointss = params[:points]
        customername = params[:customer_name]
        if Card.where(customer_name: customername, phone_number: phoneno, business_name: bizname).blank?
            @card = Card.new
            @card.points = pointss
            @card.business_name = bizname
            @card.phone_number = phoneno
            @card.customer_name = customername
            @card.bizlogo = current_business.bizlogo
            if /^\d{10,10}$/.match(phoneno) and /^\d+/.match(pointss)
                if @card.save
                    redirect_to '/business_options', notice: "Success"
                else
                    redirect_to '/business/add_card', notice:"The phone number you entered cannot be saved."
                end
            else
                redirect_to '/business/add_card', notice:"The phone number and/or points you entered is invalid."
            end
        else
            redirect_to '/business/add_card', notice: "The card with the phone number "+phoneno.to_s()+" already exists for "+bizname.to_s()+"."
        end
    end
    
    def new
        @business = Business.new
    end
    
    def create 
      sparams = user_params
      if sparams[:business].empty?
          redirect_to '/business_signup', notice: "You must enter a name for your business."
      elsif not Business.where(username: sparams[:username]).blank?
          redirect_to '/business_signup', notice: "The username "+sparams[:username]+" already exists."
      else
        @business = Business.new(sparams) 
        if @business.save!
            session[:business_id] = @business.id 
            redirect_to '/business_options' 
        else 
            redirect_to '/business_signup', notice: "Your business could not be saved in the system."
        end
      end
    end
    
    private
      def user_params
        params.require(:business).permit(:business, :username, :email, :bizlogo, :password)
      end
end

app/helpers/business_helper.rb
module BusinessHelper
end

app/views/businesses/add_card.html.erb
<h2><em>Add a new card here!</em></h2>

<%= form_tag({controller: "businesses", action: "do_add_card"}, method: "patch", class: "add_card_form") do %>
  <%= label_tag(:phone_number, "Customer's name: ") %>
  <%= text_field_tag(:customer_name)%></br>
  <%= label_tag(:phone_number, "Customer's phone number: ") %>
  <%= text_field_tag(:phone_number)%></br>
  <%= label_tag(:points, "Points earned:") %>
  <%= text_field_tag(:points) %></br>
  <%= submit_tag("Add card") %>
<% end %>
<%= link_to "Back to business homepage", business_options_path %>

app/views/businesses/business_view_cards.html.erb
<div class="container">
    <% @cards.each do |card| %> 
      <div class="Card_business">
      Name: <%= h truncate(card.customer_name, :length => 15)%><br />
      Phone Number: <%= card.phone_number %><br />
      Points: <%= card.points %>
      </div><br />
      <% end %>
</div>
<%= link_to "Back to business homepage", business_options_path %>

app/views/businesses/new.html.erb
<h1><em>Sign up for Businesses</em></h1>

  <%= form_for(@business) do |f| %>
    <%= f.text_field :business, :placeholder => "Business name" %><br />
    <%= f.text_field :username, :placeholder => "Username" %><br />
    <%= f.email_field :email, :placeholder => "Email" %><br />
    <%= f.password_field :password, :placeholder => "Password" %><br />
    <%= f.file_field :bizlogo %><br />
    <%= f.submit "Sign Up", class: "btn-submit" %>
  <% end %>

app/views/businesses/options.html.erb
<div class="container">
    <%= link_to "Add a card", business_add_card_path %>
</div>
<div class="container">
    <%= link_to "Update a card", business_update_card_path %>
</div>
<div class="container">
    <%= link_to "View all cards", business_view_cards_path %>
</div>

app/views/businesses/update_card.html.erb
<h2><em>Update a card here!</em></h2>

<%= form_tag({controller: "businesses", action: "check_phone_number"}, method: "patch", class: "business_form") do %>
  <%= label_tag(:phone_number, "Phone Number:") %>
  <%= text_field_tag(:phone_number) %></br>
  <%= label_tag(:points, "Points:") %>
  <%= text_field_tag(:points) %></br>
  <%= submit_tag 'Add' %>
  <%= submit_tag 'Deduct' %>
<% end %>

<%= link_to "Back to business homepage", business_options_path %>