config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'customer' => 'customer#customer_view_cards'
  get 'customer/customer_add_phonenumber_to_account' => 'customer#add_phonenumber_to_account'
  patch 'customer/do_add_phonenumber_to_account' => 'customer#do_add_phonenumber_to_account'
  
  get 'business_signup'  => 'businesses#new' 
  resources :businesses
  
  get '/business_login' => 'sessions#business_new'
  post '/business_login' => 'sessions#business_create'
  delete 'business_logout' => 'sessions#business_destroy'
  
  get 'business_options' => 'businesses#options'
  get 'business_view_cards' => 'businesses#business_view_cards'
  get 'business/update_card' => 'businesses#update_card'
  patch 'business/something' => 'businesses#check_phone_number'
  get 'business/add_card' => 'businesses#add_card'
  patch 'business/do_add_card' => 'businesses#do_add_card'
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :cards

end

app/models/customer.rb
class Customer < ActiveRecord::Base
    #TODO give all these cards to the User model
    has_many :card
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
    
    def add_phonenumber_to_account
    end
    
    def do_add_phonenumber_to_account
        phoneno = params[:phonenumber]
        if User.where(phonenumber: phoneno).empty?
            if User.where(:name => current_user)
                #@phonenumber = phoneno
                if /^\d{10,10}$/.match(phoneno)
                    if current_user.update(phonenumber: phoneno)
                        redirect_to '/customer/', notice: "Welcome to Treat Yo' Self!"
                    else
                        redirect_to '/customer/customer_add_phonenumber_to_account', notice:"The phone number you entered cannot be saved."
                    end
                else
                    redirect_to '/customer/customer_add_phonenumber_to_account', notice:"The phone number you entered is invalid."
                end
            end
        else
            redirect_to '/customer/customer_add_phonenumber_to_account', notice:"The phone number you entered is already used."
        end
    end
    
    def customer_view_cards
        phoneno = current_user.phonenumber
        @cards = Card.order("business_name ASC").where(phone_number: phoneno)

        if params[:search]
            @cards = Card.search(params[:search]).where(phone_number: phoneno).order("business_name ASC")
        else
            @cards = Card.order("business_name ASC").where(phone_number: phoneno)
        end
    end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customer/add_phonenumber_to_account.html.erb
<h2><em>Please enter phone number in format of ##########</em></h2>

<%= form_tag({controller: "customer", action: "do_add_phonenumber_to_account"}, method: "patch", class: "do_add_phonenumber_to_account_form") do %>
  <%= label_tag(:phonenumber, "Phone Number:") %>
  <%= text_field_tag(:phonenumber) %>
  <%= submit_tag("Enter") %>
<% end %>

app/views/customer/customer_add_phonenumber_to_account.html.erb
<h2><em>Please enter phone number in format of ##########</em></h2>

<%= form_tag({controller: "customer", action: "do_add_phonenumber_to_account"}, method: "patch", class: "do_add_phonenumber_to_account_form") do %>
  <%= label_tag(:phonenumber, "Phone Number:") %>
  <%= text_field_tag(:phonenumber) %>
  <%= submit_tag("Enter") %>
<% end %>

app/views/customer/customer_not_found.html.erb
<div class = "container" >
    Phone number is not found. Please click the link below to enter in a correct phone number.
    <%=link_to 'Click here', customer_path %>
</div>
    

    

app/views/customer/customer_view_cards.html.erb
<div class="search-bar">
<%= form_tag(customer_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Businesses by Name" %>
  <%= submit_tag "Search" %>
<% end %>
</div>

<div class="container">
    <% @cards.each do |card| %> 
      <div class="Card_customer">
      <div class="cardlogo"><%= image_tag card.bizlogo, class: "bizlogo" %></div>
      <div class="cardname"><%= h truncate(card.business_name, :length => 15) %>:</div><div class="cardpts"><%= card.points %></div>
      </div><br />
      <% end %>
</div>