config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'customer' => 'customer#customer_view_cards'
  get 'customer/customer_add_phonenumber_to_account' => 'customer#add_phonenumber_to_account'
  patch 'customer/do_add_phonenumber_to_account' => 'customer#do_add_phonenumber_to_account'
  
  get 'business_signup'  => 'businesses#new' 
  resources :businesses
  
  get '/business_login' => 'sessions#business_new'
  post '/business_login' => 'sessions#business_create'
  delete 'business_logout' => 'sessions#business_destroy'
  
  get 'business_options' => 'businesses#options'
  get 'business_view_cards' => 'businesses#business_view_cards'
  get 'business/update_card' => 'businesses#update_card'
  patch 'business/something' => 'businesses#check_phone_number'
  get 'business/add_card' => 'businesses#add_card'
  patch 'business/do_add_card' => 'businesses#do_add_card'
  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :cards

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TreatYoSelf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'templated-breadth/default.css', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header id="header-wrapper">
  <div id="header" class="container">
    <div id="logo" style="padding-left: 20pt;">
      <h1><a href="#">Treat Yo' Self</a></h1><br />
      <strong>Plentiful Perks -- know what you've earned!</strong>
    </div>
    <div id="menu">
      <ul>
        <li class="page_item">
          <% if current_user %>
            Welcome <strong><%= current_user.name %></strong>!
          <% elsif current_business %>
            Welcome <strong><%= current_business.business %></strong>!
          <% end %>
        </li>
        <li>
          <% if current_business %>
            <%= image_tag current_business.bizlogo.url, class: "bizlogo" %>
          <% end %>
        </li>
        <li class="page_item">
          <% if current_business %>
            <a href="/business_options" accesskey="1" title="">Home</a>
          <%elsif current_user %>
            <a href="/customer" accesskey="1" title="">Home</a>
          <% else %>
            <a href="/" accesskey="1" title="">Home</a>
          <% end %>
        </li>
        <li class="page_item">
          <% if current_user %>
            <%= link_to "Log out", logout_path %>
          <% elsif not current_business %>
            <%= link_to "View Your Rewards with Facebook", "/auth/facebook" %>
          <% end %>
        </li>
        <li class="page_item">
          <% if not current_business and not current_user %>
            <a href="/business_signup" accesskey="1" title="">Business Signup</a>
          <% end %>
        </li>
        <li class="page_item">
          <% if current_business %>
            <%= link_to "Log out", business_logout_path, method: "delete" %>
          <% elsif not current_user %>
            <%= link_to "Business Login", "/business_login" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <div>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>
</header>

  <div id="wrapper">
    <%= yield %>
  
  </div>
  <div id="copyright" class="container">
    <p>Photo from <a href="http://www.nextviewtechnologies.com/incentivesrebate-rewards.html">Nextview Technologies</a>
    | Design by <a href="http://templated.co" rel="nofollow">TEMPLATED</a>.</p>
  </div>
  <footer>
    <strong>TreatYoSelf</strong>
  </footer>
</body>
</html>